development:
  adapter: postgresql
  database: circleapp_development
  encoding: utf8
  template: template0
  host: localhost

test:
    adapter: postgresql
    database: circleapp_test
    encoding: utf8
    template: template0
    host: localhost
